//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlykhachsan2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InHoaDon
    {
        public int MaHD { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> MaPT { get; set; }
        public string Trưởng_Đoàn { get; set; }
        public Nullable<int> TongSoPhong { get; set; }
        public Nullable<int> TongTienDV { get; set; }
        public Nullable<int> TongTienPhong { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> SoPhong { get; set; }
        public string Trưởng_Phòng { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public Nullable<int> TongNgay { get; set; }
        public Nullable<int> TienPhong { get; set; }
        public Nullable<int> TienDV { get; set; }
        public Nullable<int> Tien { get; set; }
    }
}
